### ISSUE TITLE
Updating components unpredictable

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#94]
In general, components in Arcadia seem to work as expected *most* of the time. However, there have been cases when used in production that components have behaved strangely.

In summary:

- Edited Arcadia components will sometimes not update in the scene
- This makes iterating on components attached to GameObjects unpredictable
- We are able to generate components at compile time, run time, and in the REPL that violate Unity's assumptions
- We do not know how Unity looks up components when deserializing prefabs and scenes

What follows is a detailed account of our understanding of this problem

## Components in Unity and Arcadia
Our `defcomponent` form expands to `defclass`, a wrapper for Clojure's `deftype` that we patched into the compiler to support emitting named classes with inheritance. This is not something that Clojure supports by design, but something we need in order to integrate with Unity. AOT compiling a file with `defcomponent` forms in it will correctly emit classes into the DLL that Unity can consume, and returns the type of the class it just emitted.

To add a component to a GameObject in C# one uses [AddComponent](http://docs.unity3d.com/ScriptReference/GameObject.AddComponent.html). It has two relevant forms

```csharp
go.AddComponent("ComponentName"); // add by string
go.AddComponent(typeof(ComponentType)); // add by type
```

There is a third, generic form that you typically use in C#, but it can be seen from the bytecode that it simple calls the add by type overload. 

In Arcadia this is

```clojure
(.. go (AddComponent "ComponentName"))
(.. go (AddComponent ComponentName))
```

We do not know what the lookup semantics of the string overload are, but a good guess is that they resemble the slow path in ClojureCLR's `RT.classForName`.

We seem to be able to add a freshly created component to GameObjects, meaning that `AddComponent` is probably instantiating whatever type it gets and adding that to the GameObject's component internal list. This works from the REPL

```clojure
user=> (.. (UnityEngine.GameObject.) (AddComponent (defcomponent Fresh [^float f ^UnityEngine.Vector3 p])))
#<Fresh New Game Object (user.Fresh)>
```

And sure enough, the component shows up on the GameObject, shown here in Debug mode where InstanceID and Local Identifier In File are visible

![](http://cl.ly/Z4qv/.png)

InstanceID is assigned a value, but Local Identifier In File is 0 because the scene has not been saved yet. Also note that the Script field is blank.

This component *does not survive into play mode*. After hitting play, we see

![](http://cl.ly/Z4m3/.png)

And the component never comes back. We know that Unity will flush the Mono VM at certain times, e.g. when entering play mode or compiling a new C# script. Everything in memory disappears, and then Unity uses its serialization mechanism to recreate the game's relevant state. As far as we can tell, they do this to reproduce the environment of a freshly deployed game, or to allow hot swapping of code without the complexities of state leakage.

What it comes down to is that anything that cannot be serialized will not survive for very long. In Clojure terms, anything that is not AOT'd will be blown away and not recreated.

Compare all this to a C# component from a recent project

![](http://cl.ly/Z5CK/.png)

Script here is tied to the Hologram C# script. With the Hologram script selected in the Project tab:

```clojure
user=> (type (Selection/activeObject))
UnityEditor.MonoScript

user=> (ancestors (type (Selection/activeObject)))
#{UnityEngine.TextAsset System.Object UnityEngine.Object}
```

Hologram is a MonoScript and a TextAsset, that lives on disk. One guess is that Unity serializes the the reference to that component from the GameObject in the scene, and is able to recreate the component instance after the VM has been flushed by looking up the class in the loaded assemblies and instantiating it.

If this is true, then the value of Script is crucial because that is what ties your setup in edit mode to what Unity will recreate at runtime. It is how they bridge the pre- and post-VM flush worlds.

Saving the scene and forcing text, the serialization of the GameObject looks like

```yaml
--- !u!1 &1539235451
GameObject:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  serializedVersion: 4
  m_Component:
  - 4: {fileID: 1539235453}
  - 114: {fileID: 1539235454}
  - 114: {fileID: 1539235452}
  m_Layer: 0
  m_Name: New Game Object
  m_TagString: Untagged
  m_Icon: {fileID: 0}
  m_NavMeshLayer: 0
  m_StaticEditorFlags: 0
  m_IsActive: 1
--- !u!114 &1539235452
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 1539235451}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 0}
  m_Name: 
  m_EditorClassIdentifier: 
  f: 0
  p: {x: 0, y: 0, z: 0}
--- !u!4 &1539235453
Transform:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 1539235451}
  m_LocalRotation: {x: 0, y: 0, z: 0, w: 1}
  m_LocalPosition: {x: 0, y: 0, z: 0}
  m_LocalScale: {x: 1, y: 1, z: 1}
  m_Children: []
  m_Father: {fileID: 0}
  m_RootOrder: 2
--- !u!114 &1539235454
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 1539235451}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: f4943e9985dc943b0b3e7dd4ed0ea5d1, type: 3}
  m_Name: 
  m_EditorClassIdentifier: 
  ClipVariance: 5
  RimVariance: .5
  lightflicker: .300000012
  HoloRenderer: {fileID: 0}
  FlickerLight: {fileID: 0}
  ```

In Unity's serialization all GameObjects and components are laid out sequentially and given unique ids that allow them to reference one and other. 

The first entry in this dump is the GameObject itself, with basic data like `m_IsActive` and `m_Name`, but much more importantly with `m_Component` listing the attached components. In this case, the Transform, Hologram, and Fresh.

The notion that Unity has 'built in components' and 'user components' is a myth. Unity *only has* built in components. One of those components is called MonoBehaviour, and its job is to attach user scripts to GameObjects.

You can see this in the two MonoBehaviour entries in the dump, one for Fresh and one for Hologram. Although they're not labeled, you can tell them apart by their fields. `m_Script` is the field to compare. In the Fresh component, its value is `{fileID: 0}`, while Hologram's is `{fileID: 11500000, guid: f4943e9985dc943b0b3e7dd4ed0ea5d1, type: 3}`. The `fileID` and `guid` here are almost certainly what is allowing Unity to look up components from the Assets and re-instantiate them post-VM flush.

This, of course, is the extreme case of creating a component in the REPL. This is generally not done, but it serves to highlight where we think the problem lies.

The typical use case of components is:

1. Write a `defcomponent` form into a `.clj` file and save it
2. Arcadia's AssetPostProcessor will see the change and AOT compile your code, emitting a DLL with your component in it
3. Unity will see the new DLL, scan it for components, and integrate any it finds into its machinery

From this file

```clojure
(ns game.museum
  (:use arcadia.core)
  (:import [UnityEngine Time Resources GameObject Vector3]))

;; ... omitted irrelevant defs and defns ...

(defcomponent Crawl [^float speed
                     ^boolean spawnedNextRoom]
  (Update [this]
          (let [tf (.. this transform)
                go (.. this gameObject)]
            (.. tf (Translate 0 0 (* -1 speed Time/deltaTime)))
            (if (and (< (.. tf localPosition z) spawn-y)
                     (not spawnedNextRoom))
              (do 
                (new-room)
                (set! (.spawnedNextRoom this) true)))
            (if (< (.. tf localPosition z) end-y)
              (destroy go)))))
```

We get a component named "Crawl" that shows up in all of Unity's menus, and attaches to a GameObject as such

![](http://cl.ly/Z5U9/.png)

Note that this time it *does* get a Script value, because it is being loaded from an Asset. Checking the type as we did earlier yields the same, a MonoScript TextAsset.

```yaml
--- !u!114 &1539235452
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 1539235451}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: -144152167, guid: 354ded56d240842d9921289df64cec93, type: 3}
  m_Name: 
  m_EditorClassIdentifier: 
  speed: 0
  spawnedNextRoom: 0
```

Unity even assigns it a `fileID` and a `guid`! This is not so surprising, as components have been known to work in Arcadia for a while.

## The Problem

The problem is there are some cases where things break, and we can't reproduce them. We've observed it happening in the middle of game jams, but are unable to recreate the error case when we're ready to debug. What follows is a from-memory recount of a typical manifestation.

Say you write an Arcadia component by going through the typical use case listed above. You can now attach that component to any Game Object and it will work.

This is where it gets murky. If you *edit* the component in the `clj` file and go through the whole process again, it *usually* works. The component gets updated, and any instances of it already attached to GameObjects get updated as well. However, there are instances where old versions of the component remain attached instead, and you never see your updated component at all. We've verified via bytecode disassembly that the new code gets compiled correctly, but for whatever reason, *Unity does not seem to associate the new component with instances of the old one*.

Without an understanding of Unity's deeper parts, its blackest of black boxes, we can't say for sure why this is the case. Emitting DLLs into the Assets folder and trusting Unity to do the right thing may not be sufficient.

## The Solution

We are continuing to experiment to determine exactly what is going on, while looking into deeper forms of introspection into Unity's processes. Of course, we would greatly appreciate any advice from someone with insight as to what may be causing this.

Reproducing the bug in a controlled environment is proving difficult. Keep an eye on components if you write them, and watch this space for further updates.
